/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.project;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ImageCompression extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5874888742181899427L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ImageCompression\",\"namespace\":\"com.project\",\"fields\":[{\"name\":\"url\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}},{\"name\":\"quality\",\"type\":\"float\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ImageCompression> ENCODER =
      new BinaryMessageEncoder<ImageCompression>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ImageCompression> DECODER =
      new BinaryMessageDecoder<ImageCompression>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ImageCompression> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ImageCompression> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ImageCompression> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ImageCompression>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ImageCompression to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ImageCompression from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ImageCompression instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ImageCompression fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.List<java.lang.String> url;
  private float quality;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ImageCompression() {}

  /**
   * All-args constructor.
   * @param url The new value for url
   * @param quality The new value for quality
   */
  public ImageCompression(java.util.List<java.lang.String> url, java.lang.Float quality) {
    this.url = url;
    this.quality = quality;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return url;
    case 1: return quality;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: url = (java.util.List<java.lang.String>)value$; break;
    case 1: quality = (java.lang.Float)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'url' field.
   * @return The value of the 'url' field.
   */
  public java.util.List<java.lang.String> getUrl() {
    return url;
  }


  /**
   * Sets the value of the 'url' field.
   * @param value the value to set.
   */
  public void setUrl(java.util.List<java.lang.String> value) {
    this.url = value;
  }

  /**
   * Gets the value of the 'quality' field.
   * @return The value of the 'quality' field.
   */
  public float getQuality() {
    return quality;
  }


  /**
   * Sets the value of the 'quality' field.
   * @param value the value to set.
   */
  public void setQuality(float value) {
    this.quality = value;
  }

  /**
   * Creates a new ImageCompression RecordBuilder.
   * @return A new ImageCompression RecordBuilder
   */
  public static com.project.ImageCompression.Builder newBuilder() {
    return new com.project.ImageCompression.Builder();
  }

  /**
   * Creates a new ImageCompression RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ImageCompression RecordBuilder
   */
  public static com.project.ImageCompression.Builder newBuilder(com.project.ImageCompression.Builder other) {
    if (other == null) {
      return new com.project.ImageCompression.Builder();
    } else {
      return new com.project.ImageCompression.Builder(other);
    }
  }

  /**
   * Creates a new ImageCompression RecordBuilder by copying an existing ImageCompression instance.
   * @param other The existing instance to copy.
   * @return A new ImageCompression RecordBuilder
   */
  public static com.project.ImageCompression.Builder newBuilder(com.project.ImageCompression other) {
    if (other == null) {
      return new com.project.ImageCompression.Builder();
    } else {
      return new com.project.ImageCompression.Builder(other);
    }
  }

  /**
   * RecordBuilder for ImageCompression instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ImageCompression>
    implements org.apache.avro.data.RecordBuilder<ImageCompression> {

    private java.util.List<java.lang.String> url;
    private float quality;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.project.ImageCompression.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.url)) {
        this.url = data().deepCopy(fields()[0].schema(), other.url);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.quality)) {
        this.quality = data().deepCopy(fields()[1].schema(), other.quality);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing ImageCompression instance
     * @param other The existing instance to copy.
     */
    private Builder(com.project.ImageCompression other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.url)) {
        this.url = data().deepCopy(fields()[0].schema(), other.url);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.quality)) {
        this.quality = data().deepCopy(fields()[1].schema(), other.quality);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'url' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getUrl() {
      return url;
    }


    /**
      * Sets the value of the 'url' field.
      * @param value The value of 'url'.
      * @return This builder.
      */
    public com.project.ImageCompression.Builder setUrl(java.util.List<java.lang.String> value) {
      validate(fields()[0], value);
      this.url = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'url' field has been set.
      * @return True if the 'url' field has been set, false otherwise.
      */
    public boolean hasUrl() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'url' field.
      * @return This builder.
      */
    public com.project.ImageCompression.Builder clearUrl() {
      url = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'quality' field.
      * @return The value.
      */
    public float getQuality() {
      return quality;
    }


    /**
      * Sets the value of the 'quality' field.
      * @param value The value of 'quality'.
      * @return This builder.
      */
    public com.project.ImageCompression.Builder setQuality(float value) {
      validate(fields()[1], value);
      this.quality = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'quality' field has been set.
      * @return True if the 'quality' field has been set, false otherwise.
      */
    public boolean hasQuality() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'quality' field.
      * @return This builder.
      */
    public com.project.ImageCompression.Builder clearQuality() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ImageCompression build() {
      try {
        ImageCompression record = new ImageCompression();
        record.url = fieldSetFlags()[0] ? this.url : (java.util.List<java.lang.String>) defaultValue(fields()[0]);
        record.quality = fieldSetFlags()[1] ? this.quality : (java.lang.Float) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ImageCompression>
    WRITER$ = (org.apache.avro.io.DatumWriter<ImageCompression>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ImageCompression>
    READER$ = (org.apache.avro.io.DatumReader<ImageCompression>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.url.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.String e0: this.url) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeFloat(this.quality);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<java.lang.String> a0 = this.url;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("url").schema());
        this.url = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString();
          a0.add(e0);
        }
      }

      this.quality = in.readFloat();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.String> a0 = this.url;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.String>((int)size0, SCHEMA$.getField("url").schema());
            this.url = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.String> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.String>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.String e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString();
              a0.add(e0);
            }
          }
          break;

        case 1:
          this.quality = in.readFloat();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










