/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.project;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TextFormattingResult extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8443422085250157575L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TextFormattingResult\",\"namespace\":\"com.project\",\"fields\":[{\"name\":\"formatted\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TextFormattingResult> ENCODER =
      new BinaryMessageEncoder<TextFormattingResult>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TextFormattingResult> DECODER =
      new BinaryMessageDecoder<TextFormattingResult>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TextFormattingResult> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TextFormattingResult> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TextFormattingResult> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TextFormattingResult>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TextFormattingResult to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TextFormattingResult from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TextFormattingResult instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TextFormattingResult fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String formatted;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TextFormattingResult() {}

  /**
   * All-args constructor.
   * @param formatted The new value for formatted
   */
  public TextFormattingResult(java.lang.String formatted) {
    this.formatted = formatted;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return formatted;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: formatted = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'formatted' field.
   * @return The value of the 'formatted' field.
   */
  public java.lang.String getFormatted() {
    return formatted;
  }


  /**
   * Sets the value of the 'formatted' field.
   * @param value the value to set.
   */
  public void setFormatted(java.lang.String value) {
    this.formatted = value;
  }

  /**
   * Creates a new TextFormattingResult RecordBuilder.
   * @return A new TextFormattingResult RecordBuilder
   */
  public static com.project.TextFormattingResult.Builder newBuilder() {
    return new com.project.TextFormattingResult.Builder();
  }

  /**
   * Creates a new TextFormattingResult RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TextFormattingResult RecordBuilder
   */
  public static com.project.TextFormattingResult.Builder newBuilder(com.project.TextFormattingResult.Builder other) {
    if (other == null) {
      return new com.project.TextFormattingResult.Builder();
    } else {
      return new com.project.TextFormattingResult.Builder(other);
    }
  }

  /**
   * Creates a new TextFormattingResult RecordBuilder by copying an existing TextFormattingResult instance.
   * @param other The existing instance to copy.
   * @return A new TextFormattingResult RecordBuilder
   */
  public static com.project.TextFormattingResult.Builder newBuilder(com.project.TextFormattingResult other) {
    if (other == null) {
      return new com.project.TextFormattingResult.Builder();
    } else {
      return new com.project.TextFormattingResult.Builder(other);
    }
  }

  /**
   * RecordBuilder for TextFormattingResult instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TextFormattingResult>
    implements org.apache.avro.data.RecordBuilder<TextFormattingResult> {

    private java.lang.String formatted;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.project.TextFormattingResult.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.formatted)) {
        this.formatted = data().deepCopy(fields()[0].schema(), other.formatted);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing TextFormattingResult instance
     * @param other The existing instance to copy.
     */
    private Builder(com.project.TextFormattingResult other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.formatted)) {
        this.formatted = data().deepCopy(fields()[0].schema(), other.formatted);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'formatted' field.
      * @return The value.
      */
    public java.lang.String getFormatted() {
      return formatted;
    }


    /**
      * Sets the value of the 'formatted' field.
      * @param value The value of 'formatted'.
      * @return This builder.
      */
    public com.project.TextFormattingResult.Builder setFormatted(java.lang.String value) {
      validate(fields()[0], value);
      this.formatted = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'formatted' field has been set.
      * @return True if the 'formatted' field has been set, false otherwise.
      */
    public boolean hasFormatted() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'formatted' field.
      * @return This builder.
      */
    public com.project.TextFormattingResult.Builder clearFormatted() {
      formatted = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TextFormattingResult build() {
      try {
        TextFormattingResult record = new TextFormattingResult();
        record.formatted = fieldSetFlags()[0] ? this.formatted : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TextFormattingResult>
    WRITER$ = (org.apache.avro.io.DatumWriter<TextFormattingResult>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TextFormattingResult>
    READER$ = (org.apache.avro.io.DatumReader<TextFormattingResult>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.formatted);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.formatted = in.readString();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.formatted = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










