/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.project;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class WordCountResult extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8825185830277453567L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WordCountResult\",\"namespace\":\"com.project\",\"fields\":[{\"name\":\"counts\",\"type\":{\"type\":\"map\",\"values\":\"int\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WordCountResult> ENCODER =
      new BinaryMessageEncoder<WordCountResult>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WordCountResult> DECODER =
      new BinaryMessageDecoder<WordCountResult>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<WordCountResult> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<WordCountResult> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<WordCountResult> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<WordCountResult>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this WordCountResult to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a WordCountResult from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a WordCountResult instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static WordCountResult fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.Map<java.lang.String,java.lang.Integer> counts;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WordCountResult() {}

  /**
   * All-args constructor.
   * @param counts The new value for counts
   */
  public WordCountResult(java.util.Map<java.lang.String,java.lang.Integer> counts) {
    this.counts = counts;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return counts;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: counts = (java.util.Map<java.lang.String,java.lang.Integer>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'counts' field.
   * @return The value of the 'counts' field.
   */
  public java.util.Map<java.lang.String,java.lang.Integer> getCounts() {
    return counts;
  }


  /**
   * Sets the value of the 'counts' field.
   * @param value the value to set.
   */
  public void setCounts(java.util.Map<java.lang.String,java.lang.Integer> value) {
    this.counts = value;
  }

  /**
   * Creates a new WordCountResult RecordBuilder.
   * @return A new WordCountResult RecordBuilder
   */
  public static com.project.WordCountResult.Builder newBuilder() {
    return new com.project.WordCountResult.Builder();
  }

  /**
   * Creates a new WordCountResult RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WordCountResult RecordBuilder
   */
  public static com.project.WordCountResult.Builder newBuilder(com.project.WordCountResult.Builder other) {
    if (other == null) {
      return new com.project.WordCountResult.Builder();
    } else {
      return new com.project.WordCountResult.Builder(other);
    }
  }

  /**
   * Creates a new WordCountResult RecordBuilder by copying an existing WordCountResult instance.
   * @param other The existing instance to copy.
   * @return A new WordCountResult RecordBuilder
   */
  public static com.project.WordCountResult.Builder newBuilder(com.project.WordCountResult other) {
    if (other == null) {
      return new com.project.WordCountResult.Builder();
    } else {
      return new com.project.WordCountResult.Builder(other);
    }
  }

  /**
   * RecordBuilder for WordCountResult instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WordCountResult>
    implements org.apache.avro.data.RecordBuilder<WordCountResult> {

    private java.util.Map<java.lang.String,java.lang.Integer> counts;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.project.WordCountResult.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.counts)) {
        this.counts = data().deepCopy(fields()[0].schema(), other.counts);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing WordCountResult instance
     * @param other The existing instance to copy.
     */
    private Builder(com.project.WordCountResult other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.counts)) {
        this.counts = data().deepCopy(fields()[0].schema(), other.counts);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'counts' field.
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.Integer> getCounts() {
      return counts;
    }


    /**
      * Sets the value of the 'counts' field.
      * @param value The value of 'counts'.
      * @return This builder.
      */
    public com.project.WordCountResult.Builder setCounts(java.util.Map<java.lang.String,java.lang.Integer> value) {
      validate(fields()[0], value);
      this.counts = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'counts' field has been set.
      * @return True if the 'counts' field has been set, false otherwise.
      */
    public boolean hasCounts() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'counts' field.
      * @return This builder.
      */
    public com.project.WordCountResult.Builder clearCounts() {
      counts = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WordCountResult build() {
      try {
        WordCountResult record = new WordCountResult();
        record.counts = fieldSetFlags()[0] ? this.counts : (java.util.Map<java.lang.String,java.lang.Integer>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WordCountResult>
    WRITER$ = (org.apache.avro.io.DatumWriter<WordCountResult>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WordCountResult>
    READER$ = (org.apache.avro.io.DatumReader<WordCountResult>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.counts.size();
    out.writeMapStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.Integer> e0: this.counts.entrySet()) {
      actualSize0++;
      out.startItem();
      out.writeString(e0.getKey());
      java.lang.Integer v0 = e0.getValue();
      out.writeInt(v0);
    }
    out.writeMapEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readMapStart();
      java.util.Map<java.lang.String,java.lang.Integer> m0 = this.counts; // Need fresh name due to limitation of macro system
      if (m0 == null) {
        m0 = new java.util.HashMap<java.lang.String,java.lang.Integer>((int)size0);
        this.counts = m0;
      } else m0.clear();
      for ( ; 0 < size0; size0 = in.mapNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.String k0 = null;
          k0 = in.readString();
          java.lang.Integer v0 = null;
          v0 = in.readInt();
          m0.put(k0, v0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readMapStart();
          java.util.Map<java.lang.String,java.lang.Integer> m0 = this.counts; // Need fresh name due to limitation of macro system
          if (m0 == null) {
            m0 = new java.util.HashMap<java.lang.String,java.lang.Integer>((int)size0);
            this.counts = m0;
          } else m0.clear();
          for ( ; 0 < size0; size0 = in.mapNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.String k0 = null;
              k0 = in.readString();
              java.lang.Integer v0 = null;
              v0 = in.readInt();
              m0.put(k0, v0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










